
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '8i\xcd?T\xea\x1fW)\xd3a\x84\xba\xae\x95v'
    
_lr_action_items = {'REGPREFIX':([2,3,5,15,16,],[6,6,6,6,6,]),'SW':([0,1,4,9,14,19,20,],[2,-2,2,-1,-5,-4,-3,]),'NUMBER':([6,7,8,10,11,],[11,12,13,14,-6,]),'LBRACKET':([12,13,],[15,16,]),'LW':([0,1,4,9,14,19,20,],[3,-2,3,-1,-5,-4,-3,]),'LUI':([0,1,4,9,14,19,20,],[5,-2,5,-1,-5,-4,-3,]),'RBRACKET':([11,17,18,],[-6,19,20,]),'$end':([1,4,9,14,19,20,],[-2,0,-1,-5,-4,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[4,]),'instruction':([0,4,],[1,9,]),'register':([2,3,5,15,16,],[7,8,10,17,18,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program instruction','program',2,'p_program','parser.py',18),
  ('program -> instruction','program',1,'p_program','parser.py',19),
  ('instruction -> LW register NUMBER LBRACKET register RBRACKET','instruction',6,'p_lw','parser.py',30),
  ('instruction -> SW register NUMBER LBRACKET register RBRACKET','instruction',6,'p_sw','parser.py',38),
  ('instruction -> LUI register NUMBER','instruction',3,'p_lui','parser.py',46),
  ('register -> REGPREFIX NUMBER','register',2,'p_register','parser.py',54),
]
